#!/bin/bash

USR_DIR=/home/chli4934/UsydCodeLab/learn_tf/t2t/problem_demo
PROBLEM=poetry_lines
DATA_DIR=$USR_DIR/t2t_data
TMP_DIR=/tmp/t2t_datagen

t2t-datagen \
    --t2t_usr_dir=$USR_DIR \
    --data_dir=$DATA_DIR \
    --tmp_dir=$TMP_DIR \
    --problem=$PROBLEM
